
spring.servlet.multipart.max-file-size: 40GB
spring.servlet.multipart.max-request-size: 40GB

springdoc.swagger-ui.path: /

logging:
  level:
#    web: trace
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: trace # To display mappings
